config/routes.rb
ExceptionCanary::Dashboard.routes.draw do
  root to: 'groups#index'

  resources :groups, except: [:new, :create] do
    get 'page/:page', action: :index, on: :collection
    get ':id/page/:page', action: :show, on: :collection
  end

  resources :stored_exceptions, only: [:index, :show] do
    get 'page/:page', action: :index, on: :collection
  end
end

app/models/exception_canary/group.rb
module ExceptionCanary
  class Group < ActiveRecord::Base
    has_many :stored_exceptions

    validates :name, presence: true
    validates :action, presence: true
    validates :match_type, presence: true
    validates :value, presence: true
    validate :note_if_suppressing

    attr_accessible :name, :action, :match_type, :value, :note, :is_auto_generated

    calculated :exceptions_count, -> { 'select count(*) from exception_canary_stored_exceptions where exception_canary_stored_exceptions.group_id = exception_canary_groups.id' }
    calculated :most_recent_exception, -> { 'select max(created_at) from exception_canary_stored_exceptions where exception_canary_stored_exceptions.group_id = exception_canary_groups.id' }

    ACTION_NOTIFY   = 10
    ACTION_SUPPRESS = 20
    ACTIONS = [ACTION_NOTIFY, ACTION_SUPPRESS]

    MATCH_TYPE_EXACT = 10
    MATCH_TYPE_REGEX = 20
    MATCH_TYPES = [MATCH_TYPE_EXACT, MATCH_TYPE_REGEX]

    def notify?
      action == ACTION_NOTIFY
    end

    def suppress?
      action == ACTION_SUPPRESS
    end

    def exact?
      match_type == MATCH_TYPE_EXACT
    end

    def short_value
      lines = value.split("\n").first
    end

    def auto_generated?
      is_auto_generated
    end

    def matches?(exception)
      case match_type
      when MATCH_TYPE_EXACT
        exception.title == value
      when MATCH_TYPE_REGEX
        !Regexp.new(value).match(exception.title).nil?
      end
    end

    private

    def note_if_suppressing
      errors.add(:note, 'must be populated when suppressing notifications.') if suppress? && note.blank?
    end
  end
end

app/models/exception_canary/rule.rb
module ExceptionCanary
  class Rule < ActiveRecord::Base
    has_many :stored_exceptions

    validates :name, presence: true
    validates :action, presence: true
    validates :match_type, presence: true
    validates :value, presence: true

    attr_accessible :name, :action, :match_type, :value, :is_auto_generated

    calculated :exceptions_count, -> { 'select count(*) from exception_canary_stored_exceptions where exception_canary_stored_exceptions.rule_id = exception_canary_rules.id' }
    calculated :most_recent_exception, -> { 'select max(created_at) from exception_canary_stored_exceptions where exception_canary_stored_exceptions.rule_id = exception_canary_rules.id' }

    ACTION_NOTIFY   = 10
    ACTION_SUPPRESS = 20
    ACTIONS = [ACTION_NOTIFY, ACTION_SUPPRESS]

    MATCH_TYPE_EXACT = 10
    MATCH_TYPE_REGEX = 20
    MATCH_TYPES = [MATCH_TYPE_EXACT, MATCH_TYPE_REGEX]

    def notify?
      action == ACTION_NOTIFY
    end

    def suppress?
      action == ACTION_SUPPRESS
    end

    def auto_generated?
      is_auto_generated
    end

    def matches?(exception)
      case match_type
      when MATCH_TYPE_EXACT
        exception.title == value
      when MATCH_TYPE_REGEX
        !Regexp.new(value).match(exception.title).nil?
      end
    end
  end
end

app/models/exception_canary/stored_exception.rb
module ExceptionCanary
  class StoredException < ActiveRecord::Base
    belongs_to :group

    paginates_per 50

    attr_accessible :title, :backtrace, :environment, :variables, :klass

    serialize :environment
    serialize :variables

    scope :exception_search, -> (term) { where('title LIKE ?', "%#{term}%") }

    def backtrace_summary
      if backtrace.length < 300
        backtrace
      else
        "#{backtrace[0...297]}..."
      end
    end

    def short_title
      title.split("\n").first
    end
  end
end

app/controllers/exception_canary/application_controller.rb
module ExceptionCanary
  class ApplicationController < ActionController::Base; end
end

app/controllers/exception_canary/groups_controller.rb
require_dependency 'exception_canary/application_controller'

module ExceptionCanary
  class GroupsController < ApplicationController
    helper_method :sort_column, :sort_direction

    def index
      @groups = Group.scoped.calculated(:exceptions_count, :most_recent_exception).order(sort_param).page(params[:page])
    end

    def show
      @group = Group.find(params[:id])
      @stored_exceptions = @group.stored_exceptions.page(params[:page])
    end

    def edit
      @group = Group.find(params[:id])
    end

    def update
      @group = Group.find(params[:id])
      params[:group][:value].gsub!("\r\n", "\n") if params[:group][:value]
      if @group.update_attributes(params[:group].merge(is_auto_generated: false))
        reclassified_msg = flash_num_reclassified(reclassify_exceptions)
        redirect_to @group, flash: { notice: "Updated group and reclassified #{reclassified_msg}." }
      else
        render :edit
      end
    end

    def destroy
      group = Group.find(params[:id])
      group.destroy
      redirect_to groups_path, flash: { notice: 'Deleted group.' }
    end

    private

    def sort_param
      "#{sort_column} #{sort_direction}"
    end

    def sort_column
      Group.column_names.concat(%w(exceptions_count most_recent_exception)).include?(params[:sort]) ? params[:sort] : 'most_recent_exception'
    end

    def sort_direction
      default = sort_column == 'most_recent_exception' ? 'desc' : 'asc'
      %w(asc desc).include?(params[:direction]) ? params[:direction] : default
    end

    def reclassify_exceptions
      exceptions_reclassified = 0
      StoredException.all.each do |se|
        if se.group == @group
          unless @group.matches? se
            se.group = nil
            se.save!
            exceptions_reclassified += 1
          end
        elsif @group.matches? se
          old_group = se.group
          se.group = @group
          se.save!
          old_group.destroy if old_group && old_group.auto_generated? && old_group.stored_exceptions.empty?
          exceptions_reclassified += 1
        end
      end
      exceptions_reclassified
    end

    def flash_num_reclassified(num_reclassified)
      ActionController::Base.helpers.pluralize(num_reclassified, 'exception')
    end
  end
end

app/controllers/exception_canary/stored_exceptions_controller.rb
require_dependency 'exception_canary/application_controller'

module ExceptionCanary
  class StoredExceptionsController < ApplicationController
    def index
      base =
        if params[:term].present?
          StoredException.exception_search(params[:term])
        else
          StoredException
        end
      @stored_exceptions = base.order(:created_at).reverse_order.page(params[:page])
    end

    def show
      @stored_exception = StoredException.find(params[:id])
    end
  end
end

app/helpers/exception_canary/application_helper.rb
module ExceptionCanary
  module ApplicationHelper
    def format_time(time)
      time = Time.parse(time) if time.is_a? String
      time.strftime('%Y-%m-%d %H:%M:%S')
    end
  end
end

app/helpers/exception_canary/groups_helper.rb
module ExceptionCanary
  module GroupsHelper
    def sortable(column, title = nil)
      title ||= column.titleize
      icon =
        if column == sort_column
          (sort_direction == 'asc' ? '<i class="icon-chevron-up"></i>' : '<i class="icon-chevron-down"></i>')
        end
      css_class = column == sort_column ? 'current' : nil
      direction = column == sort_column && sort_direction == 'asc' ? 'desc' : 'asc'
      link_to "#{title} #{icon}".html_safe, { sort: column, direction: direction }, class: css_class
    end

    def action_name(action)
      case action
      when Group::ACTION_NOTIFY
        'Notify'
      when Group::ACTION_SUPPRESS
        'Suppress'
      end
    end

    def match_type_name(match_type)
      case match_type
      when Group::MATCH_TYPE_EXACT
        'Exact'
      when Group::MATCH_TYPE_REGEX
        'Regex'
      end
    end
  end
end

app/helpers/exception_canary/rules_helper.rb
module ExceptionCanary
  module RulesHelper
    def sortable(column, title = nil)
      title ||= column.titleize
      icon =
        if column == sort_column
          (sort_direction == 'asc' ? '<i class="icon-chevron-up"></i>' : '<i class="icon-chevron-down"></i>')
        end
      css_class = column == sort_column ? 'current' : nil
      direction = column == sort_column && sort_direction == 'asc' ? 'desc' : 'asc'
      link_to "#{title} #{icon}".html_safe, { sort: column, direction: direction }, class: css_class
    end

    def action_name(action)
      case action
      when Rule::ACTION_NOTIFY
        'Notify'
      when Rule::ACTION_SUPPRESS
        'Suppress'
      end
    end

    def match_type_name(match_type)
      case match_type
      when Rule::MATCH_TYPE_EXACT
        'Exact'
      when Rule::MATCH_TYPE_REGEX
        'Regex'
      end
    end
  end
end

app/helpers/exception_canary/stored_exceptions_helper.rb
module ExceptionCanary
  module StoredExceptionsHelper
  end
end

app/views/exception_canary/groups/edit.html.erb
<% content_for :title, 'Edit Group' %>

<h4>Edit Group</h4>
 
<%= form_for @group do |f| %>
  <% if @group.errors.any? %>
    <div id='error_explanation'>
      <div class='alert alert-error'>
        <%= pluralize(@group.errors.count, 'error') %> prohibited this group from being saved:
        <ul>
          <% @group.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
          </ul>
      </div>
    </div>
  <% end %>
  <fieldset>
    <%= f.label :name %>
    <%= f.text_field :name %>
   
    <%= f.label :action %>
    <%= f.select :action, ExceptionCanary::Group::ACTIONS.map { |a| [action_name(a), a] } %>

    <%= f.label :match_type %>
    <%= f.select :match_type, ExceptionCanary::Group::MATCH_TYPES.map { |m| [match_type_name(m), m] } %>

    <%= f.label :value %>
    <%= f.text_area :value %>

    <%= f.label :note %>
    <%= f.text_area :note %>

    <p>Note: When defining a regex value, you must escape parentheses and other regex operators, e.g. \(StandardError\) not (StandardError)</p>
   
    <br>
    <%= f.submit %>
  </fieldset>
<% end %>

app/views/exception_canary/groups/index.html.erb
<% content_for :title, 'Groups' %>

<table class='table groups'>
  <thead>
    <tr>
      <th><%= sortable 'name' %></th>
      <th><%= sortable 'action' %></th>
      <th><%= sortable 'value', 'Exception Message' %></th>
      <th><%= sortable 'exceptions_count', 'Matched Exceptions' %></th>
      <th><%= sortable 'most_recent_exception', 'Most Recent Exception' %></th>
    </tr>
  </thead>
  <tbody>
    <% @groups.each do |group| %>
      <tr <%= 'class="warning"' if group.notify? %>>
        <td><%= link_to group.name, group %></td>
        <td><%= action_name(group.action) %></td>
        <td><%= group.short_value %></td>
        <td><%= group.exceptions_count %></td>
        <td><%= group.most_recent_exception.nil? ? 'None' : format_time(group.most_recent_exception) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @groups %>

app/views/exception_canary/groups/show.html.erb
<% content_for :title, "Group: #{@group.name}" %>

<h4>Name:</h4>
<%= @group.name %>
<hr>

<% if @group.note %>
  <h4>Note:</h4>
  <%= @group.note %>
  <hr>
<% end %>

<table class='table'>
  <thead>
    <tr>
      <th>Action</th>
      <th>Match Type</th>
      <th>Matched Exceptions</th>
      <th>Most Recent Exception</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= action_name(@group.action) %></td>
      <td><%= match_type_name(@group.match_type) %></td>
      <td><%= @group.exceptions_count %>
      <td><%= @group.most_recent_exception.nil? ? 'None' : format_time(@group.most_recent_exception) %>
    </tr>
  </tbody>
</table>

<hr>
<% if @group.notify? %>
  <%= link_to 'Switch to Suppress', group_path(@group, group: { action: ExceptionCanary::Group::ACTION_SUPPRESS }), method: :put, class: 'btn' %>
<% else %>
  <%= link_to 'Switch to Notify', group_path(@group, group: { action: ExceptionCanary::Group::ACTION_NOTIFY }), method: :put, class: 'btn' %>
<% end %>
<%= link_to 'Edit', edit_group_path(@group), class: 'btn' %>
<%= link_to 'Delete', group_path(@group), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn right' %>

<hr>
<h4>Exception <%= @group.exact? ? 'Message' : 'Regex' %></h4>
<%= simple_format @group.value %>

<% unless @group.exceptions_count == 0 %>
  <hr>
  <h4>Matched Exceptions</h4>
  <%= render partial: 'exception_canary/stored_exceptions/table', locals: { stored_exceptions: @stored_exceptions, hide_group: true } %>
<% end %>