config/routes.rb
ExceptionCanary::Dashboard.routes.draw do
  root to: 'groups#index'

  resources :groups, except: [:new, :create] do
    get 'page/:page', action: :index, on: :collection
    get ':id/page/:page', action: :show, on: :collection
  end

  resources :stored_exceptions, only: [:index, :show] do
    get 'page/:page', action: :index, on: :collection
  end
end

app/models/exception_canary/group.rb
module ExceptionCanary
  class Group < ActiveRecord::Base
    has_many :stored_exceptions

    validates :name, presence: true
    validates :action, presence: true
    validates :match_type, presence: true
    validates :value, presence: true
    validate :note_if_suppressing

    attr_accessible :name, :action, :match_type, :value, :note, :is_auto_generated

    calculated :exceptions_count, -> { 'select count(*) from exception_canary_stored_exceptions where exception_canary_stored_exceptions.group_id = exception_canary_groups.id' }
    calculated :most_recent_exception, -> { 'select max(created_at) from exception_canary_stored_exceptions where exception_canary_stored_exceptions.group_id = exception_canary_groups.id' }

    ACTION_NOTIFY   = 10
    ACTION_SUPPRESS = 20
    ACTIONS = [ACTION_NOTIFY, ACTION_SUPPRESS]

    MATCH_TYPE_EXACT = 10
    MATCH_TYPE_REGEX = 20
    MATCH_TYPES = [MATCH_TYPE_EXACT, MATCH_TYPE_REGEX]

    def notify?
      action == ACTION_NOTIFY
    end

    def suppress?
      action == ACTION_SUPPRESS
    end

    def exact?
      match_type == MATCH_TYPE_EXACT
    end

    def short_value
      lines = value.split("\n").first
    end

    def auto_generated?
      is_auto_generated
    end

    def matches?(exception)
      case match_type
      when MATCH_TYPE_EXACT
        exception.title == value
      when MATCH_TYPE_REGEX
        !Regexp.new(value).match(exception.title).nil?
      end
    end

    private

    def note_if_suppressing
      errors.add(:note, 'must be populated when suppressing notifications.') if suppress? && note.blank?
    end
  end
end

app/models/exception_canary/rule.rb
module ExceptionCanary
  class Rule < ActiveRecord::Base
    has_many :stored_exceptions

    validates :name, presence: true
    validates :action, presence: true
    validates :match_type, presence: true
    validates :value, presence: true

    attr_accessible :name, :action, :match_type, :value, :is_auto_generated

    calculated :exceptions_count, -> { 'select count(*) from exception_canary_stored_exceptions where exception_canary_stored_exceptions.rule_id = exception_canary_rules.id' }
    calculated :most_recent_exception, -> { 'select max(created_at) from exception_canary_stored_exceptions where exception_canary_stored_exceptions.rule_id = exception_canary_rules.id' }

    ACTION_NOTIFY   = 10
    ACTION_SUPPRESS = 20
    ACTIONS = [ACTION_NOTIFY, ACTION_SUPPRESS]

    MATCH_TYPE_EXACT = 10
    MATCH_TYPE_REGEX = 20
    MATCH_TYPES = [MATCH_TYPE_EXACT, MATCH_TYPE_REGEX]

    def notify?
      action == ACTION_NOTIFY
    end

    def suppress?
      action == ACTION_SUPPRESS
    end

    def auto_generated?
      is_auto_generated
    end

    def matches?(exception)
      case match_type
      when MATCH_TYPE_EXACT
        exception.title == value
      when MATCH_TYPE_REGEX
        !Regexp.new(value).match(exception.title).nil?
      end
    end
  end
end

app/models/exception_canary/stored_exception.rb
module ExceptionCanary
  class StoredException < ActiveRecord::Base
    belongs_to :group

    paginates_per 50

    attr_accessible :title, :backtrace, :environment, :variables, :klass

    serialize :environment
    serialize :variables

    scope :exception_search, -> (term) { where('title LIKE ?', "%#{term}%") }

    def backtrace_summary
      if backtrace.length < 300
        backtrace
      else
        "#{backtrace[0...297]}..."
      end
    end

    def short_title
      title.split("\n").first
    end
  end
end

app/controllers/exception_canary/application_controller.rb
module ExceptionCanary
  class ApplicationController < ActionController::Base; end
end

app/controllers/exception_canary/groups_controller.rb
require_dependency 'exception_canary/application_controller'

module ExceptionCanary
  class GroupsController < ApplicationController
    helper_method :sort_column, :sort_direction

    def index
      @groups = Group.scoped.calculated(:exceptions_count, :most_recent_exception).order(sort_param).page(params[:page])
    end

    def show
      @group = Group.find(params[:id])
      @stored_exceptions = @group.stored_exceptions.page(params[:page])
    end

    def edit
      @group = Group.find(params[:id])
    end

    def update
      @group = Group.find(params[:id])
      params[:group][:value].gsub!("\r\n", "\n") if params[:group][:value]
      if @group.update_attributes(params[:group].merge(is_auto_generated: false))
        reclassified_msg = flash_num_reclassified(reclassify_exceptions)
        redirect_to @group, flash: { notice: "Updated group and reclassified #{reclassified_msg}." }
      else
        render :edit
      end
    end

    def destroy
      group = Group.find(params[:id])
      group.destroy
      redirect_to groups_path, flash: { notice: 'Deleted group.' }
    end

    private

    def sort_param
      "#{sort_column} #{sort_direction}"
    end

    def sort_column
      Group.column_names.concat(%w(exceptions_count most_recent_exception)).include?(params[:sort]) ? params[:sort] : 'most_recent_exception'
    end

    def sort_direction
      default = sort_column == 'most_recent_exception' ? 'desc' : 'asc'
      %w(asc desc).include?(params[:direction]) ? params[:direction] : default
    end

    def reclassify_exceptions
      exceptions_reclassified = 0
      StoredException.all.each do |se|
        if se.group == @group
          unless @group.matches? se
            se.group = nil
            se.save!
            exceptions_reclassified += 1
          end
        elsif @group.matches? se
          old_group = se.group
          se.group = @group
          se.save!
          old_group.destroy if old_group && old_group.auto_generated? && old_group.stored_exceptions.empty?
          exceptions_reclassified += 1
        end
      end
      exceptions_reclassified
    end

    def flash_num_reclassified(num_reclassified)
      ActionController::Base.helpers.pluralize(num_reclassified, 'exception')
    end
  end
end

app/controllers/exception_canary/stored_exceptions_controller.rb
require_dependency 'exception_canary/application_controller'

module ExceptionCanary
  class StoredExceptionsController < ApplicationController
    def index
      base =
        if params[:term].present?
          StoredException.exception_search(params[:term])
        else
          StoredException
        end
      @stored_exceptions = base.order(:created_at).reverse_order.page(params[:page])
    end

    def show
      @stored_exception = StoredException.find(params[:id])
    end
  end
end

app/helpers/exception_canary/application_helper.rb
module ExceptionCanary
  module ApplicationHelper
    def format_time(time)
      time = Time.parse(time) if time.is_a? String
      time.strftime('%Y-%m-%d %H:%M:%S')
    end
  end
end

app/helpers/exception_canary/groups_helper.rb
module ExceptionCanary
  module GroupsHelper
    def sortable(column, title = nil)
      title ||= column.titleize
      icon =
        if column == sort_column
          (sort_direction == 'asc' ? '<i class="icon-chevron-up"></i>' : '<i class="icon-chevron-down"></i>')
        end
      css_class = column == sort_column ? 'current' : nil
      direction = column == sort_column && sort_direction == 'asc' ? 'desc' : 'asc'
      link_to "#{title} #{icon}".html_safe, { sort: column, direction: direction }, class: css_class
    end

    def action_name(action)
      case action
      when Group::ACTION_NOTIFY
        'Notify'
      when Group::ACTION_SUPPRESS
        'Suppress'
      end
    end

    def match_type_name(match_type)
      case match_type
      when Group::MATCH_TYPE_EXACT
        'Exact'
      when Group::MATCH_TYPE_REGEX
        'Regex'
      end
    end
  end
end

app/helpers/exception_canary/rules_helper.rb
module ExceptionCanary
  module RulesHelper
    def sortable(column, title = nil)
      title ||= column.titleize
      icon =
        if column == sort_column
          (sort_direction == 'asc' ? '<i class="icon-chevron-up"></i>' : '<i class="icon-chevron-down"></i>')
        end
      css_class = column == sort_column ? 'current' : nil
      direction = column == sort_column && sort_direction == 'asc' ? 'desc' : 'asc'
      link_to "#{title} #{icon}".html_safe, { sort: column, direction: direction }, class: css_class
    end

    def action_name(action)
      case action
      when Rule::ACTION_NOTIFY
        'Notify'
      when Rule::ACTION_SUPPRESS
        'Suppress'
      end
    end

    def match_type_name(match_type)
      case match_type
      when Rule::MATCH_TYPE_EXACT
        'Exact'
      when Rule::MATCH_TYPE_REGEX
        'Regex'
      end
    end
  end
end

app/helpers/exception_canary/stored_exceptions_helper.rb
module ExceptionCanary
  module StoredExceptionsHelper
  end
end

app/views/exception_canary/stored_exceptions/_table.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>Timestamp</th>
      <th>Message</th>
      <th>Class</th>
      <% unless defined?(hide_group) && hide_group %>
        <th>Group</th>
      <% end %>
    </tr>
  </thead>
  <tbody>
    <% @stored_exceptions.each do |se| %>
      <tr>
        <td><%= link_to format_time(se.created_at), se %></td>
        <td><%= se.short_title %></td>
        <td><%= se.klass %></td>
        <% unless defined?(hide_group) && hide_group %>
          <td>
            <% if se.group %>
              <% if se.group.name == se.title %>
                <%= link_to se.group.id, se.group %>
              <% else %>
                <%= link_to se.group.name, se.group %>
              <% end %>
            <% else %>
              None
            <% end %>
          </td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @stored_exceptions %>

app/views/exception_canary/stored_exceptions/index.html.erb
<% content_for :title, 'Stored Exceptions' %>

<form class='form-search' action='<%= stored_exceptions_path %>' method='get'>
  <input type='text' name='term' class='input-medium search-query' value='<%= params[:term] %>'>
  <button type='submit' class='btn'>Search</button>
  <% if params[:term].present? %>
    <%= link_to 'Clear', stored_exceptions_path, class: 'btn' %>
  <% end %>
</form>

<%= render partial: 'table', locals: { stored_exceptions: @stored_exceptions } %>

app/views/exception_canary/stored_exceptions/show.html.erb
<% content_for :title, "Stored Exception: #{@stored_exception.title}" %>

<h4>Exception Message</h4>
<%= simple_format @stored_exception.title %>
<h5>Class: <%= @stored_exception.klass %></h5>

<% if @stored_exception.group %>
  <hr>
  <h4>Group</h4>
  <p><%= link_to @stored_exception.group.name, @stored_exception.group %></p>
  <p>
    Group action: 
    <% if @stored_exception.group.notify? %>
      <b>Notify</b><br><%= link_to 'Switch to Suppress', group_path(@stored_exception.group, group: { action: ExceptionCanary::Group::ACTION_SUPPRESS }), method: :put, class: 'btn' %>
    <% else %>
      <b>Suppress</b><br><%= link_to 'Switch to Notify', group_path(@stored_exception.group, group: { action: ExceptionCanary::Group::ACTION_NOTIFY }), method: :put, class: 'btn' %>
    <% end %>
  </p>
<% end %>

<hr>
<h4>Backtrace</h4>
<div class='backtrace'>
  <%= simple_format @stored_exception.backtrace %>
</div>
<%= link_to 'Show More', '#', id: 'show-more' %>

<% if @stored_exception.variables %>
  <hr>
  <h4>Variables</h4>
  <table class='table'>
    <thead>
      <tr>
        <th>Name</th>
        <th>Value</th>
      </tr>
    </thead>
    <tbody>
      <% @stored_exception.variables.each do |k, v| %>
        <tr>
          <td><%= k %></td>
          <td><%= v %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

<% if @stored_exception.environment %>
  <hr>
  <h4>Environment</h4>
  <table class='table'>
    <thead>
      <tr>
        <th>Name</th>
        <th>Value</th>
      </tr>
    </thead>
    <tbody>
      <% @stored_exception.environment.each do |k, v| %>
        <tr>
          <td><%= k %></td>
          <td><%= v %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>